node {
  cookie = "thesis-streaming-cookie"
  data_dir = "/opt/emqx/data"
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
}

dashboard.listeners.http {
  bind = 18083
}

connectors.kafka_producer.kafka_ingress {
  enable = true
  bootstrap_hosts = "kafka:9092"
}

actions.kafka_producer.raw_incomplete_to_kafka {
  enable = true
  connector = "kafka_ingress"
  parameters {
    topic = "thesis.raw.incomplete"
    message {
      key = "${clientid}"
      value = "${payload}"
    }
  }
}

rule_engine.rules.mqtt_raw_to_kafka {
  enable = true
  sql = "SELECT payload, clientid, topic, timestamp FROM \"thesis/raw\""
  actions = ["kafka_producer:raw_incomplete_to_kafka"]
}
